import 'package:flutter/material.dart';

List<Offset> yellowHomePath = [
  const Offset(1, 10),
  const Offset(1, 13),
  const Offset(4, 10),
  const Offset(4, 13),
];

List<Offset> yellowPath = [
  //yellow
  const Offset(0, 8),
  const Offset(1, 8),
  const Offset(2, 8),
  const Offset(3, 8),
  const Offset(4, 8),
  const Offset(5, 8),
  const Offset(6, 9),
  const Offset(6, 10),
  const Offset(6, 11),
  const Offset(6, 12),
  const Offset(6, 13),
  const Offset(6, 14),
  const Offset(7, 14),
  const Offset(8, 14),
  const Offset(8, 13),
  const Offset(8, 12),
  const Offset(8, 11),
  const Offset(8, 10),
  const Offset(8, 9),
  const Offset(9, 8),
  const Offset(10, 8),
  const Offset(11, 8),
  const Offset(12, 8),
  const Offset(13, 8),
  const Offset(14, 8),
  const Offset(14, 7),
  const Offset(14, 6),
  const Offset(13, 6),
  const Offset(12, 6),
  const Offset(11, 6),
  const Offset(10, 6),
  const Offset(9, 6),
  const Offset(8, 5),
  const Offset(8, 4),
  const Offset(8, 3),
  const Offset(8, 2),
  const Offset(8, 1),
  const Offset(8, 0),
  const Offset(7, 0),
  const Offset(6, 0),
  const Offset(6, 1),
  const Offset(6, 2),
  const Offset(6, 3),
  const Offset(6, 4),
  const Offset(6, 5),
  const Offset(5, 6),
  const Offset(4, 6),
  const Offset(3, 6),
  const Offset(2, 6),
  const Offset(1, 6),
  const Offset(0, 6),
  const Offset(0, 7),
  const Offset(1, 7),
  const Offset(2, 7),
  const Offset(3, 7),
  const Offset(4, 7),
  const Offset(5, 7),
  const Offset(6, 7),
];
